// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrainInfoSystem.Data;

#nullable disable

namespace TrainInfoSystem.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250511125053_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TrainInfoSystem.Models.Booking", b =>
                {
                    b.Property<int>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingId"));

                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("JourneyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PassengerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrainId")
                        .HasColumnType("int");

                    b.HasKey("BookingId");

                    b.HasIndex("ClassId");

                    b.HasIndex("TrainId");

                    b.ToTable("Bookings");

                    b.HasData(
                        new
                        {
                            BookingId = 1,
                            ClassId = 1,
                            Email = "amit.sharma@example.com",
                            JourneyDate = new DateTime(2025, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PassengerName = "Amit Sharma",
                            TrainId = 1
                        },
                        new
                        {
                            BookingId = 2,
                            ClassId = 2,
                            Email = "priya.patel@example.com",
                            JourneyDate = new DateTime(2025, 6, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PassengerName = "Priya Patel",
                            TrainId = 1
                        },
                        new
                        {
                            BookingId = 3,
                            ClassId = 3,
                            Email = "rahul.gupta@example.com",
                            JourneyDate = new DateTime(2025, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PassengerName = "Rahul Gupta",
                            TrainId = 2
                        },
                        new
                        {
                            BookingId = 4,
                            ClassId = 2,
                            Email = "sneha.verma@example.com",
                            JourneyDate = new DateTime(2025, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PassengerName = "Sneha Verma",
                            TrainId = 3
                        },
                        new
                        {
                            BookingId = 5,
                            ClassId = 4,
                            Email = "vikram.singh@example.com",
                            JourneyDate = new DateTime(2025, 6, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PassengerName = "Vikram Singh",
                            TrainId = 3
                        });
                });

            modelBuilder.Entity("TrainInfoSystem.Models.Class", b =>
                {
                    b.Property<int>("ClassId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClassId"));

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClassId");

                    b.ToTable("Classes");

                    b.HasData(
                        new
                        {
                            ClassId = 1,
                            ClassName = "First AC"
                        },
                        new
                        {
                            ClassId = 2,
                            ClassName = "AC 2 Tier"
                        },
                        new
                        {
                            ClassId = 3,
                            ClassName = "AC 3 Tier"
                        },
                        new
                        {
                            ClassId = 4,
                            ClassName = "Sleeper"
                        });
                });

            modelBuilder.Entity("TrainInfoSystem.Models.Fare", b =>
                {
                    b.Property<int>("TrainId")
                        .HasColumnType("int");

                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.Property<int>("AvailableSeats")
                        .HasColumnType("int");

                    b.Property<decimal>("FareAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TotalSeats")
                        .HasColumnType("int");

                    b.HasKey("TrainId", "ClassId");

                    b.HasIndex("ClassId");

                    b.ToTable("Fares");

                    b.HasData(
                        new
                        {
                            TrainId = 1,
                            ClassId = 1,
                            AvailableSeats = 15,
                            FareAmount = 4500.00m,
                            TotalSeats = 20
                        },
                        new
                        {
                            TrainId = 1,
                            ClassId = 2,
                            AvailableSeats = 30,
                            FareAmount = 3000.00m,
                            TotalSeats = 40
                        },
                        new
                        {
                            TrainId = 1,
                            ClassId = 3,
                            AvailableSeats = 50,
                            FareAmount = 2000.00m,
                            TotalSeats = 60
                        },
                        new
                        {
                            TrainId = 1,
                            ClassId = 4,
                            AvailableSeats = 70,
                            FareAmount = 600.00m,
                            TotalSeats = 80
                        },
                        new
                        {
                            TrainId = 2,
                            ClassId = 1,
                            AvailableSeats = 10,
                            FareAmount = 4000.00m,
                            TotalSeats = 15
                        },
                        new
                        {
                            TrainId = 2,
                            ClassId = 2,
                            AvailableSeats = 25,
                            FareAmount = 2500.00m,
                            TotalSeats = 30
                        },
                        new
                        {
                            TrainId = 2,
                            ClassId = 3,
                            AvailableSeats = 40,
                            FareAmount = 1800.00m,
                            TotalSeats = 50
                        },
                        new
                        {
                            TrainId = 3,
                            ClassId = 1,
                            AvailableSeats = 12,
                            FareAmount = 4200.00m,
                            TotalSeats = 18
                        },
                        new
                        {
                            TrainId = 3,
                            ClassId = 2,
                            AvailableSeats = 28,
                            FareAmount = 2800.00m,
                            TotalSeats = 35
                        },
                        new
                        {
                            TrainId = 3,
                            ClassId = 3,
                            AvailableSeats = 45,
                            FareAmount = 1900.00m,
                            TotalSeats = 55
                        });
                });

            modelBuilder.Entity("TrainInfoSystem.Models.PNR", b =>
                {
                    b.Property<int>("PNRId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PNRId"));

                    b.Property<string>("BerthNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<string>("Coach")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PNRNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SeatNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PNRId");

                    b.HasIndex("BookingId")
                        .IsUnique();

                    b.ToTable("PNRs");

                    b.HasData(
                        new
                        {
                            PNRId = 1,
                            BerthNumber = "10",
                            BookingId = 1,
                            Coach = "H1",
                            PNRNumber = "PNR123456789",
                            SeatNo = "10A",
                            Status = "Confirmed"
                        },
                        new
                        {
                            PNRId = 2,
                            BerthNumber = "15",
                            BookingId = 2,
                            Coach = "A1",
                            PNRNumber = "PNR234567890",
                            SeatNo = "15B",
                            Status = "Confirmed"
                        },
                        new
                        {
                            PNRId = 3,
                            BerthNumber = "20",
                            BookingId = 3,
                            Coach = "B2",
                            PNRNumber = "PNR345678901",
                            SeatNo = "20C",
                            Status = "Waiting"
                        },
                        new
                        {
                            PNRId = 4,
                            BerthNumber = "25",
                            BookingId = 4,
                            Coach = "A2",
                            PNRNumber = "PNR456789012",
                            SeatNo = "25A",
                            Status = "Confirmed"
                        },
                        new
                        {
                            PNRId = 5,
                            BerthNumber = "30",
                            BookingId = 5,
                            Coach = "S1",
                            PNRNumber = "PNR567890123",
                            SeatNo = "30D",
                            Status = "RAC"
                        });
                });

            modelBuilder.Entity("TrainInfoSystem.Models.Train", b =>
                {
                    b.Property<int>("TrainId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TrainId"));

                    b.Property<string>("TrainName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrainNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TrainId");

                    b.ToTable("Trains");

                    b.HasData(
                        new
                        {
                            TrainId = 1,
                            TrainName = "Rajdhani Express",
                            TrainNumber = "12951"
                        },
                        new
                        {
                            TrainId = 2,
                            TrainName = "Shatabdi Express",
                            TrainNumber = "12009"
                        },
                        new
                        {
                            TrainId = 3,
                            TrainName = "Duronto Express",
                            TrainNumber = "12245"
                        });
                });

            modelBuilder.Entity("TrainInfoSystem.Models.Booking", b =>
                {
                    b.HasOne("TrainInfoSystem.Models.Class", "Class")
                        .WithMany()
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrainInfoSystem.Models.Train", "Train")
                        .WithMany("Bookings")
                        .HasForeignKey("TrainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Train");
                });

            modelBuilder.Entity("TrainInfoSystem.Models.Fare", b =>
                {
                    b.HasOne("TrainInfoSystem.Models.Class", "Class")
                        .WithMany("Fare")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrainInfoSystem.Models.Train", "Train")
                        .WithMany("Fare")
                        .HasForeignKey("TrainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Train");
                });

            modelBuilder.Entity("TrainInfoSystem.Models.PNR", b =>
                {
                    b.HasOne("TrainInfoSystem.Models.Booking", "Booking")
                        .WithOne("PNR")
                        .HasForeignKey("TrainInfoSystem.Models.PNR", "BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("TrainInfoSystem.Models.Booking", b =>
                {
                    b.Navigation("PNR")
                        .IsRequired();
                });

            modelBuilder.Entity("TrainInfoSystem.Models.Class", b =>
                {
                    b.Navigation("Fare");
                });

            modelBuilder.Entity("TrainInfoSystem.Models.Train", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Fare");
                });
#pragma warning restore 612, 618
        }
    }
}
